{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0",
    "title": "Swagger test-Petly",
    "description": "Final project of team #7"
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "http://localhost:3000" }],
  "tags": [
    {
      "name": "users",
      "description": "Operations about user"
    },
    {
      "name": "pets",
      "description": "Everything about your Pets"
    },
    {
      "name": "news",
      "description": "News endpoints"
    },
    {
      "name": "sponsors",
      "description": "Sponsors endpoints"
    }
  ],
  "paths": {
    "/api/users/signup": {
      "post": {
        "tags": ["users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Email in use",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/api/users/signin": {
      "post": {
        "tags": ["users"],
        "summary": "Logs user into the system",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },
    "/api/users/logout": {
      "post": {
        "tags": ["users"],
        "summary": "Logout user into the system",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "Authorization": {
          "description": "Logout object",
          "required": true,
          "content": {
            "application/json": {}
          }
        },
        "responses": {
          "204": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/api/users/current": {
      "get": {
        "tags": ["users"],
        "summary": "User current",
        "parameters": [],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "User's info was received",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/api/news": {
      "get": {
        "tags": ["news"],
        "summary": "Receiving news",
        "parameters": [],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNewsResponse"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/api/sponsors": {
      "get": {
        "tags": ["sponsors"],
        "summary": "Project sponsors",
        "parameters": [],

        "responses": {
          "200": {
            "description": "Sponsors received",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSponsorsResponse"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/api/pets": {
      "post": {
        "tags": ["pets"],
        "summary": "Adding animal user card",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Pet description",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PetRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Pet was added",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PetResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/api/pets/petId": {
      "delete": {
        "tags": ["pets"],
        "summary": "Pet was deleted",
        "parameters": [
          {
            "in": "path",
            "name": "petId",
            "required": true,
            "type": "string",
            "description": "pet ID"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Delete object",
          "required": true,
          "content": {
            "application/json": {}
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "phone": {
            "type": "string",
            "description": "User's phone"
          },
          "city": {
            "type": "string",
            "description": "User's city"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            },
            "name": {
              "type": "string",
              "description": "User's name"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "phone": {
              "type": "string",
              "description": "User's phone"
            },
            "city": {
              "type": "string",
              "description": "User's city"
            },
            "birthday": {
              "type": "string",
              "description": "Date of Birth"
            }
          }
        },
        "example": {
          "user": {
            "name": "Toni",
            "email": "starc@gmail.com",
            "birthday": "null",
            "phone": "900-45-45",
            "city": "Dnipro"
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "token": {
              "type": "string",
              "description": "token"
            },
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            },
            "name": {
              "type": "string",
              "description": "User's name"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "phone": {
              "type": "string",
              "description": "User's phone"
            },
            "city": {
              "type": "string",
              "description": "User's city"
            },
            "birthday": {
              "type": "string",
              "description": "Date of Birth"
            }
          }
        },
        "example": {
          "token": "string",
          "user": {
            "name": "Toni",
            "email": "starc@gmail.com",
            "birthday": "null",
            "phone": "900-45-45",
            "city": "Dnipro"
          }
        }
      },
      "CurrentResponse": {
        "type": "object",
        "items": {
          "data": "object",
          "properties": {
            "data": {
              "type": "object",
              "description": "Object current"
            }
          }
        },
        "example": {
          "data": {
            "type": "object",
            "description": "Object information about users"
          }
        }
      },
      "GetNewsResponse": {
        "type": "object",
        "items": {
          "data": "object",
          "properties": {
            "data": {
              "type": "object",
              "description": "Object news"
            }
          }
        },
        "example": {
          "data": {
            "type": "object",
            "description": "Object information about news"
          }
        }
      },
      "GetSponsorsResponse": {
        "type": "object",
        "items": {
          "data": "object",
          "properties": {
            "data": {
              "type": "object",
              "description": "Object sponsors"
            }
          }
        },
        "example": {
          "data": {
            "type": "object",
            "description": "Object information about sponsors"
          }
        }
      },
      "PetRequest": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Pet name"
            },
            "birthday": {
              "type": "string",
              "description": "pet's birthday"
            },
            "breed": {
              "type": "string",
              "description": "pet's breed"
            },
            "comments": {
              "type": "string",
              "description": "comments owner"
            }
          }
        },
        "example": {
          "name": "tirecs",
          "birthday": "01.02.22",
          "breed": "dog",
          "comments": "La lala bla blabla"
        }
      },
      "PetResponse": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Pet name"
            },
            "birthday": {
              "type": "string",
              "description": "pet's birthday"
            },
            "breed": {
              "type": "string",
              "description": "pet's breed"
            },
            "comments": {
              "type": "string",
              "description": "comments owner"
            }
          }
        },
        "example": {
          "owner": {
            "name": "tirecs",
            "birthday": "01.02.22",
            "breed": "dog",
            "comments": "La lala bla blabla"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
